#!/bin/sh
module="wdt"
device="wdt"
mode="666"

# Group: since distributions do it differently, look for wheel or use staff
if grep '^staff:' /etc/group > /dev/null; then
    group="staff"
else
    group="wheel"
fi

# invoke modprobe with all arguments
/sbin/modprobe $module

major=`cat /proc/devices | awk "\\$2==\"$module\" {print \\$1}"`

# Create desired entry points
# Add nodes as required in modprobe above
rm -f /dev/${device}
mknod /dev/${device} c $major 0

chgrp $group /dev/${device}
chmod $mode  /dev/${device}
